# Generated by Django 5.0.3 on 2024-03-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmblog', '0003_post_preview_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(blank=True),
        ),
    ]
