# Generated by Django 5.0.3 on 2024-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmblog', '0004_alter_post_body_alter_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
