# Generated by Django 5.0.3 on 2024-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmblog', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
