# Generated by Django 5.0.3 on 2024-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmblog', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
